### ISSUE TITLE
Can't open LOG1

### ISSUE THREAD

**Issue by davidak** [allardhoeve/bombard#3]
I always get this error:

**Can't open LOG1: No such file or directory at /usr/local/bin/bombard line 87, <RC> line 20.**

i run it with `bombard -f /root/bomb.txt -l /root/bombdir/ -i 10 -r 3 -s 10 -t 1`

the directory `/root/bombdir/` exists but is always empty.

i also tried to set `logfile = /tmp/siege.log` in `.siegerc` with the same result.

**Comment by allardhoeve** [comment]
Hey there. I think maybe the error message could be a little better: https://github.com/allardhoeve/bombard/blob/ed599d6f6e86359524ebc3fb50aedcb5e011c789/src/bombard.in#L87

You could try editing that error message by making that line look like:

``` perl
open LOG1, $logf or die "Can't open LOG1 at '$logf': $!";
```

At least you'll see the location `bombard` is trying to open :)

**Comment by allardhoeve** [comment]
Otherwise, try this: https://github.com/klokantech/bombard-docker

**Comment by davidak** [comment]
**Can't open LOG1 at '/tmp/siege.log': No such file or directory at /usr/local/bin/bombard line 87, <RC> line 20.**

i removed `-l` and changed the path in `.siegerc` to `/root/siege.log`

**Can't open LOG1 at '/root/siege.log': No such file or directory at /usr/local/bin/bombard line 87, <RC> line 22.**

So i think the problem is that siege is not writing the file.

i also tried to set `logging = true` in `.siegerc` but no change.

actually i had to set `logging = true` in `.siege/siege.conf` what is the new configuration in siege 4.0.2 i think.
