### ISSUE TITLE
Chance of mac support

### ISSUE THREAD

**Issue by alexbowers** [allardhoeve/bombard#5]
Is there any chance of getting mac support (via brew) for this? It's nice to use on ubuntu, but being able to use on the host machine would be nice

**Comment by allardhoeve** [comment]
Hey there. I've never made a brew recipe before and do not currently use this on Mac, so... But you're welcome to PR a recipe if you create/find one. Thanks.

**Comment by alexbowers** [comment]
I'll take a look at this sometime soon then :)

**Comment by apilkarki2** [comment]
@allardhoeve  Executing the following command, it throws an exception : 
   >>>> _bombard -f /home/test/Desktop/file.txt -i10 -r10 -s50 -t1_
**Can't open .siegerc: No such file or directory**
Then using
  >>  _siege.config_

**usage: siege.config [no arguments]
----------------------------------
Resource file already install as /home/test/.siege/siege.conf
Use your favorite editor to change  your configuration by
editing the values in that file or remove it and run this
program again.**
